### PR TITLE
Add throttle listener while switching cameras

### PR DESCRIPTION
**Pull request by sam5727**
Fix issue #237

### CODE REVIEW

**Comment by madisp** [comment]
I'm not a maintainer but IMHO this is something that should be fixed in CameraX itself rather than patching around it with throttling - the latter can be brittle as the bug will still happen if the device/camera hardware is slow enough.

**Comment by sam5727** [comment]
Yeah, you're right. It should sth be fixed in CarmeaX library instead.
The way I did is just try to avoid the crash before library fixed.

**Comment by owahltinez** [comment]
Please see my [latest comment](https://github.com/android/camera-samples/issues/237#issuecomment-649068139), fortunately this will be fixed very shortly!

**Comment by sam5727** [comment]
Updated on #284

**Pull request closed without merging**
