### PR TITLE
Change all left/right to start/end

### PR DESCRIPTION
**Pull request by zhaonian**

### CODE REVIEW

**Comment by owahltinez** [comment]
Hey @zhaonian thanks for thinking about this. What's the rationale for this change? All the items that use left/right references are UI elements that have no reason to change based on the device's left-to-right or right-to-left settings.

**Comment by zhaonian** [comment]
I used the `Analyze > Inspect Code...` in Android Studio to surface some style issues and I found these RTL issues raised by Android Studio. However, I did not notice these fragments do not rely on the orientation settings . 😅sry about this!
I think it's fine to just close this PR.

**Comment by owahltinez** [comment]
Well, if we are not changing the attributes, them maybe we should add some annotations to prevent the linter from flagging this issue...

**Comment by zhaonian** [comment]
How about this? 
added `android:layoutDirection` to enforce `ltr`, so we can ensure it's LTR, and also able to remove those RTL-related lint warnings.

**Pull request merged**
