### PR TITLE
Fix broken link in README

### PR DESCRIPTION
**Pull request by jcgoble3**
The README had a link that went to GitHub's 404 page. So I fixed it.

### CODE REVIEW

**Comment by jcgoble3** [comment]
Do I really need to go through the whole CLA process just to fix a broken link in a text file?

**Comment by jcgoble3** [comment]
*sigh* Alright then. :P

**Comment by jcgoble3** [comment]
@googlebot I signed it!

**Comment by owahltinez** [comment]
Thanks for submitting this @jcgoble3 (and for jumping through the hoops the googlebot makes us all go through)

**Pull request merged**
