### PR TITLE
upgrade to cameraX 1.0.0-alpha06

### PR DESCRIPTION
**Pull request by bazted**

### CODE REVIEW

**Comment by bazted** [comment]
@googlebot I signed it!

**Comment by bazted** [comment]
@owahltinez I have tried to apply requested changes.

**Comment by owahltinez** [comment]
Hi @bazted, thank you for applying the requested changes. Very unfortunately, a change that we thought was abandoned was pushed to the our internal mirror of this repo causing some pretty gnarly conflicts.

Even though the change already updates the sample to `alpha06`, I think your PR has some very useful things I would love to include -- like your well-documented function choosing which aspect ratio to apply. If you are up for it and can work out the conflicts, I'd be happy to move forward with your PR.

You can probably get rid of your AppExecutors implementation, the current branch solves this in a pretty succint way (although I'm open to your opinion about that).

**Comment by bazted** [comment]
I have rebased and resolved conflicts. 

I removed AppExecutors like you suggested though I am not happy that taking picture logic will run on the main thread. Its pretty heavy task(writing to a file), though I am not sure if CameraX does not use its internal executors for this task.

**Comment by owahltinez** [comment]
Thanks @bazted, this looks great. You have a good point about the executor being on the main thread. If you want to, you can change `ContextCompat.getMainExecutor(requireContext())` to something like `Executors.newSingleThreadExecutor()` -- I'll leave up to you if you want to make that change, it looks good as-is to me so just let me know. I mainly thought that creating a whole new class for this purpose was overkill.

**Comment by bazted** [comment]
Let us leave it as it is. Thanks for great cooperation.

**Comment by owahltinez** [comment]
Merged!

**Pull request merged**
