### PR TITLE
Ignore dummy preparation exception to avoid crash

### LINKED ISSUE #285: IOException: prepare failed on Pixel3a Simulator
Please follow the following instructions before filing a bug:

1. Github issues under this project are only for **sample**-related issues. If you have modified the sample code in any way, then this is probably not the appropriate place to report a bug.
1. If you are trying to report a bug related to the **CameraX library** then you can do so at the Android Issue Tracker: https://issuetracker.google.com/components/618491.
1. Include the specific sample where you found the issue, in addition to device model and specific Android build number -- which can be found under Settings > About phone.
1. Include error logs from logcat, if there are any.
1. If you can, also attach a [bug report](https://developer.android.com/studio/debug/bug-report)-- but please keep in mind that personal information can sometimes be found in those, so double check before attaching.
## Environment
- Pixel 3a , Android 10(Build Number QSR1.190920.001, x86)

```
2020-08-26 15:02:43.354 30125-30125/com.android.example.camera2.video E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.android.example.camera2.video, PID: 30125
    java.io.IOException: prepare failed.
        at android.media.MediaRecorder._prepare(Native Method)
        at android.media.MediaRecorder.prepare(MediaRecorder.java:1065)
        at com.example.android.camera2.video.fragments.CameraFragment$recorderSurface$2.invoke(CameraFragment.kt:109)
        at com.example.android.camera2.video.fragments.CameraFragment$recorderSurface$2.invoke(CameraFragment.kt:72)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.example.android.camera2.video.fragments.CameraFragment.getRecorderSurface(Unknown Source:2)
        at com.example.android.camera2.video.fragments.CameraFragment.access$getRecorderSurface$p(CameraFragment.kt:72)
        at com.example.android.camera2.video.fragments.CameraFragment$initializeCamera$1.invokeSuspend(CameraFragment.kt:247)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

### PR DESCRIPTION
**Pull request by ecoopnet**
fix #285

### CODE REVIEW

**Comment by owahltinez** [comment]
I don't think this PR solves the underlying problem. If preparation fails, then the surface will not be appropriately allocated (at least in some devices)

**Comment by owahltinez** [comment]
Hi @ecoopnet are you still interested in merging this PR?

**Comment by ecoopnet** [comment]
Hi @owahltinez
Yes, you're right, I think it's an unnatural amendment, too.
However, we had to do this because we had a problem with pixel 3a, a widely used android device, which always crashes when applying this sample project in our project.

We have no problem with this fix on our device, but I'm wondering if some devices need preparation.

If only there was a better way...

**Comment by peerless2012** [comment]
Still crash when really to record.

**Comment by ggfan** [comment]
@peerless2012 may you add your device mode to https://github.com/android/camera-samples/issues/285? 
looks like that issue needs to be revisited, intending to close this PR.  thanks

**Pull request closed without merging**
