### PR TITLE
♻️ Convert Gradle build of this Android sample from Groovy to Kotlin

### PR DESCRIPTION
**Pull request by jmfayard**
If merged, this PR would allow to have an Android sample where the Gradle build is configured in Kotlin.

Android Studio 4.0 Preview announce support for Kotlin DSL build scripts

> Support for Kotlin DSL script files
>
> The Android Gradle plugin now supports Kotlin DSL build script files (*.kts).
> When used with Android Studio, certain IDE features, such as the Project Structure dialog and build script quick fixes,
> now also support reading and writing to Kotlin build script files.
> https://developer.android.com/studio/preview/features/

There are not a lots of Android samples using Kotlin DSL though. 

This lack of dogfooding is an issue IMHO.

Note: since [there are no Kotlin documentation in the Android Gradle Plugin documentation](https://developer.android.com/studio/build ), I worked around the problem by keeping the `android` block in Groovy. 

```kotlin
// app/build.gradle.kts, written in Kotlin
plugins {
  id("com.android.application")
  kotlin("android")
}

// here is the trick to keep the android block in Groovy
apply(from = "android.gradle")

dependencies {
   implementation("com.squareup.retrofit:retrofit:4.0")
}

-------

// android.gradle, written in Groovy
android {
 // unchanged
}
```

### CODE REVIEW

**Comment by owahltinez** [comment]
Hi @jmfayard,

First, thank you for submitting this PR. It's pretty cool! Please refer to #159 for another example of moving from gradle to kts. Please also see [my comment there](https://github.com/android/camera-samples/pull/159#issuecomment-580566509) trying to rationalize a change like this.

Other than providing an example of gradle -> kts conversion, what are your arguments for making this change?

**Comment by jmfayard** [comment]
Hello Oscar @owahltinez 

Here are some of my counter arguments

> It's not the standard for Android Studio projects

Android 4.0 says in its release notes that it will *Support for Kotlin DSL script files*. 

This is strange because on one hand it is not new, and on the other hand it is not true. 

Whether or not "it is the standard in Android Studio", it is already used because the support for landed in Gradle 4.10 (we are at Gradle 6) and in IntelliJ like 18 months ago. Which means it landed in Android Studio some time ago already.

Now unless you maintain a very old Gradle plugin written in Groovy, by default you don't have anything special to make your Gradle plugin works with both Groovy and Kotlin. The main thing the users need is documentation in both Groovy and Kotlin.

Lots of plugin provide that documentation: Kotlin, Spring, Gradle-versions-plugins, Detekt, Dex Count, Android Check 2, ...

The documentation Android Gradle Plugin currently does **not** provide Kotlin snippets at https://developer.android.com/studio/build

I can see the downside of this: developers are wasting a lot of time. 

But what is the upside of not having documentation for Kotlin users?

> Android 4.0 will have support for Kotlin DSL script files

On the other hand, this announcment would be misleading if AS was released today because there are obvious bugs in Android Studio itself.

And at that point, I am not interested in reporting them because really it's a problem of dogfooding. 

If no Android projects are using Kotlin DSL scripts, then no-one that can fix those problems will notice them.


> It makes builds slower

[CITATION_NEEDED]

Once you enable `org.gradle.caching=true` like I did, the `build.gradle.kts` compilation gets cached.

Use the build scan performance report, and you will probably see that it doesn't really matter. 

If if there is a performance bottleneck, Gradle and JetBrains will fix them like they have done already in lots of case.

> It breaks the super helpful highlighting that tells you when one of your dependencies is out of date

For people who wants to use Groovy, it doesn't matter because nobody is forcing them to use Kotlin.

For people like me using Kotlin, it doesn't really matter much because there are IMHO better options available
https://github.com/ben-manes/gradle-versions-plugin

**Comment by jmfayard** [comment]
> Kotlin makes Gradle builds slower

Build performance is important, so let see. The minimum set of steps to reproduce with this project are:

`$ ./gradlew --scan help`
_Publishing build scan..._
_https://scans.gradle.com/s/v2wbqxdjuq2r4/performance/configuration_


Screenshot_2_3_20__7_05_AM

Indeed, 6s to do nothing, this is not good. 

But what if [you enable `org.gradle.caching=true` like I did, the `build.gradle.kts` compilation gets cached](https://github.com/android/camera-samples/pull/162/files#diff-c90f093cd0656f6c1e81664532416c93).

`$ ./gradlew --scan help # with caching enabled`
_Publishing build scan..._
_https://scans.gradle.com/s/hb5c5ngq6tjac/performance/configuration_

Build_scan_for__Camera2Basic__just_now___Gradle_Cloud_Services

Oh, now I am fine with this kind of performance!!

If there are other performance bottlenecks, please report them. JetBrains and Gradle have fixed a lot of them in the past, and I am sure they would continue to do so.

**Comment by martinbonnin** [comment]
Kotlin Gradle files with autocompletion makes configuration a lot more discoverable. Being able to know and navigate to the extension javadoc is really helpful to know what options are available.
It might actually be easier for beginners that often know Kotlin better that Groovy.

**Comment by jmfayard** [comment]
@martinbonnin 
I agree with one caveat.

Here is a screencast that shows something I always wanted: adding dependencies integrated in IntelliJ or Android Studio. 

<iframe width="560" height="315" src="https://www.youtube.com/embed/VhYERonB8co" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

My caveat is that it's not even a "Kotlin versus Groovy" decision. 

It's about providing another option, supporting better people who are already using Kotlin. 

And this doesn't do harm people using Groovy in any way that I can think of.

**Comment by owahltinez** [comment]
I have consulted my colleagues and the consensus is that we will not be updating build Gradle files to kts in our official Android samples just yet. We will wait until the Android Studio and tooling support are a little more polished and available in the stable release, then we will revisit this decision.

So we'll be closing this PR for now but until we make the switch we can use it as a reference if anyone is interested in moving to kts build files. Once again, thanks for submitting this, at the very least we will be using to point people to an example.

**Comment by jmfayard** [comment]
@owahltinez yup that makes sense. I didn't intend to have this particular sample migrated to Kotlin, I wanted to open a conversation about how to solve the chicken and egg problem of Gradle Kotlin and Android studio. The way I acquired real world experience was doing backend development with Gradle, Spring and IntelliJ. this setup basically works.

**Pull request closed without merging**
